### ISSUE TITLE
warp items always show loading

### ISSUE THREAD

**Issue by 0x0006e** [ankeetmaini/react-infinite-scroll-component#213]
![image](https://user-images.githubusercontent.com/18499153/94644712-9d6bfe00-031c-11eb-95c2-c7a85cd9394e.png)

https://codesandbox.io/s/hopeful-sunset-ds5fg

**Comment by ankeetmaini** [comment]
You've hardcoded `hasMore` attribute to `true`. This should generally be dependent on whether you've more records or not. Also try to keep the initial list of items large enough to have a scroll. Otherwise, the component will not cause fetch of next items.

I'm closing this please reopen if you still face issues.
