### ISSUE TITLE
can I pass custom Style or Class to the outerDiv ?

### ISSUE THREAD

**Issue by harvinder-ss** [ankeetmaini/react-infinite-scroll-component#50]
Hi,

 I am getting an issue as I need to pass width to the outer div . Is there any way to pass ?

Thanks.,

**Comment by ankeetmaini** [comment]
You can wrap the children in your own div.

Like

<InfiniteScroll {..all properties}>
<div> // your own div
// child items
</div>
</InfiniteScroll>

**Comment by Anna-Weaver-JL** [comment]
I had the same issue - and wrapping the child items didn't help. 

The unnamed, unstyled div gets a width property that caused us some issues.  I got round it by assigning a style using `div:first-child`

**Comment by ankeetmaini** [comment]
@Anna-Weaver-JL, @harvinder-ss I know this reply is a little late. I've created a codesandbox showing this in action.

https://codesandbox.io/s/1y7jjvlwjl

See line 39, there the outer div contains a custom div which is styled in a light yellow color. I am closing this issue. Please reopen if you still face any issue.

**Comment by Anna-Weaver-JL** [comment]
Thank you @ankeetmaini - I wasn't clear enought with the issue I think.  Have a look at this sandbox where I have made replicated our issue. 

https://codesandbox.io/s/k24w99vojr

We have a grid of details each box in the grid takes a percentage of the row.  As long as our first row contains enough items to fill the row the infinite scroll works perfectly but once we have a situation were there are very few items the first display sets the size of the parent div and the percentage calculation becomes an issue.  In the sandbox above I have set the size so that 2 items show on a row.  When I set the array to start with a single item you will see that the width gets messed up.
This is because of a div coded in teh component - that I identified and re-styled using 
```
#product-grid > div:first-child > div:first-child{
  width: 100%;
}
```
with the code:
```
<div id="product-grid">
              <div className="row">
                <InfiniteScroll ...
```

**Comment by mrtheyann** [comment]
Still a problem, actually

**Comment by doanhtu07** [comment]
For now, my solution is to have a CSS file. Something like below works:

**// Example.css**
```css
.infinite-scroll-component__outerdiv {
     width: 100%;
     /* ...whatever more styles you want */
}
```

Then you just import this file to your component file. Hope it helps.

**Comment by BlueBeret** [comment]
for anyone who still need to solve the problem. My solution was:
### component
```html
<div className="infinite-scroll-container">
<InfiniteScroll />
</div>
```

### css file
```css
.infinite-scroll-container > div:first-child {
/* this styling goes to the outer div of infinite scroll */
}
```

**Comment by Ali-0235** [comment]
<div className="cover">
<InfiniteScroll />
</div>

CSS File:
.cover{
//Styling
}

**Comment by Ali-0235** [comment]
```
<div className="cover">
<InfiniteScroll />
</div>
CSS File:
.cover{
//Styling
}
```

**Comment by gilopavani** [comment]
> para quem ainda precisa resolver o problema. Minha solução foi:
> 
> ### componente
> ```
> <div className="infinite-scroll-container">
> <InfiniteScroll />
> </div>
> ```
> 
> ### Arquivo CSS
> ```css
> .infinite-scroll-container > div:first-child {
> /* this styling goes to the outer div of infinite scroll */
> }
> ```

Obrigado.
resolveu pra mim.

**Comment by d4nielchaves** [comment]
Thank you so much, @BlueBeret !
