### ISSUE TITLE
Support Server Side Rendering

### ISSUE THREAD

**Issue by mrchief** [ankeetmaini/react-infinite-scroll-component#64]
Currently, the code references `window` directly, see [this](https://github.com/ankeetmaini/react-infinite-scroll-component/blob/912d6ab7fd2f6af8fcb567047e9ba41302a301be/app/index.js#L36) and [this](https://github.com/ankeetmaini/react-infinite-scroll-component/blob/912d6ab7fd2f6af8fcb567047e9ba41302a301be/app/index.js#L161).

This breaks server side rendering since `window` is undefined. This can be fixed by using something like https://www.npmjs.com/package/window-or-global.

**Comment by ankeetmaini** [comment]
@mrchief I looked at this issue long and deep. I'm using `window` only in and after `componentDidMount`. This is safe for SSR as `componentDidMount` gets called on the client and not on the server.

To test this out, I took a React SSR boilerplate and added InfiniteScroll component in the shared bundle. And it worked without any errors. [first commit](https://github.com/ankeetmaini/infinite-scroll-ssr/tree/04bc4950841fa1b4cec453861a4bdefa258577a4)

Next, I added your dropdown component and it failed saying `window` is not defined. At this point I forked your repo, and changed the webpack mode to development so that Dropdown's code isn't minified to debug the issue. (I copy pasted the built files into this repo to access the Dropdown code)

Please see that the error was reported on line number 10, which is output of the IIFE.
<img width="790" alt="screen shot 2018-06-07 at 12 01 31 am" src="https://user-images.githubusercontent.com/6652823/41057952-1cd45700-69e6-11e8-8a77-b611efd4d74c.png">
<img width="558" alt="screen shot 2018-06-07 at 12 01 44 am" src="https://user-images.githubusercontent.com/6652823/41057959-212bd558-69e6-11e8-9daa-eed772203bde.png">

I suspect this is because of the way Webpack 4 is generating the UMD definition. I then lowered the Webpack to 2.3.4 which I'm using at work, and built the Dropdown component and it worked fine.

So I'm guessing Webpack 4 is what's causing an issue, and not the infinite scroll component. 

I made [three commits](https://github.com/ankeetmaini/infinite-scroll-ssr/commits/master) to this  [https://github.com/ankeetmaini/infinite-scroll-ssr](https://github.com/ankeetmaini/infinite-scroll-ssr) for you to see the steps.

Let me know if I can help more, and sorry for not getting to it earlier.

**Comment by ankeetmaini** [comment]
Webpack 2 generates the IIFE [like this](https://github.com/ankeetmaini/infinite-scroll-ssr/blob/31670b89cc45547001205f87055b34efdc6cff23/shared/components/DemoApp/AsyncHomeRoute/dropdown/index.js#L10) - it uses `this` instead of window

```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("react"));
	else if(typeof define === 'function' && define.amd)
		define("ReactDropdownTreeSelect", ["react"], factory);
	else if(typeof exports === 'object')
		exports["ReactDropdownTreeSelect"] = factory(require("react"));
	else
		root["ReactDropdownTreeSelect"] = factory(root["React"]);
})(this, function(__WEBPACK_EXTERNAL_MODULE_0__) {
return /******/ (function(modules) { // webpackBootstrap
```

Webpack [4 produces this](https://github.com/ankeetmaini/infinite-scroll-ssr/blob/master/shared/components/DemoApp/AsyncHomeRoute/dropdown/index.js#L10)

```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("react"));
	else if(typeof define === 'function' && define.amd)
		define("ReactDropdownTreeSelect", ["react"], factory);
	else if(typeof exports === 'object')
		exports["ReactDropdownTreeSelect"] = factory(require("react"));
	else
    root["ReactDropdownTreeSelect"] = factory(root["React"]);
})(window, function(__WEBPACK_EXTERNAL_MODULE_react__) {
return /******/ (function(modules) { // webpackBootstrap
```

**Comment by mrchief** [comment]
@ankeetmaini Thanks for this deep dive. Let me take a detailed look and get back to you. This is very helpful! :+1:

**Comment by mrchief** [comment]
Found this: https://github.com/webpack/webpack/issues/6525. Thanks again for digging into this!
