### ISSUE TITLE
window scrolling doesn't work

### ISSUE THREAD

**Issue by kdenz** [ankeetmaini/react-infinite-scroll-component#7]
Hi! why is window scrolling not working for both desktop and mobile browsers? Thank you!

**Comment by ankeetmaini** [comment]
Can you give an example? Did you checkout the usage in demos folder?

**Comment by kdenz** [comment]
@ankeetmaini yes I've ran the window scrolling demo in demos folder, and it doesn't scroll at all. Only fixed size one scrolls well. On mobile it's the same, when `height` is not provided, it doesn't scroll at all. 

Also, the mobile browsers (Chrome, Safari) doesn't auto-hide address bar and bottom navigation bar when using  fixed height scrolling content, is there a way to overcome it?

**Comment by ankeetmaini** [comment]
@kdenz I think it shouldn't trigger next call if there's no scroll I think. As I can't think of a trigger which should call.

A solution would be to load enough items so that a scroll appears. And then before user reaches bottom, next function call would be made to fetch data.

Let me know if you still feel something should be done. Meanwhile I'll update the examples to load more elements so that scroll appears on both desktop/mobile browsers.

Closing this issue, reopen if you still feel something needs to be done.

**Comment by 94younglau** [comment]
Download the repository and copy code from **demos/**,  the `next` func only trigger once.
